CC = gcc
LIB = myftp.c dir_SunOS.c -lsocket -lnsl -lpthread

all: server client

server: myftp.c myftpserver.c
		${CC} -o server myftpserver.c ${LIB} 

client:	myftp.c myftpclient.c
		${CC} -o client myftpclient.c ${LIB}  
		
clean: rm server client 
